plugins { id 'com.android.application' }

android {
    buildFeatures { buildConfig = true }
    namespace 'com.iojh2021.persiandashboard'
    compileSdk 35

    defaultConfig {
        buildConfigField 'String', 'AERODATABOX_RAPIDAPI_KEY_1', '"' + (System.getenv('AERODATABOX_RAPIDAPI_KEY_1') ?: '') + '"'
        buildConfigField 'String', 'AERODATABOX_RAPIDAPI_KEY_2', '"' + (System.getenv('AERODATABOX_RAPIDAPI_KEY_2') ?: '') + '"'
        buildConfigField 'String', 'AERODATABOX_RAPIDAPI_KEY_3', '"' + (System.getenv('AERODATABOX_RAPIDAPI_KEY_3') ?: '') + '"'
        applicationId 'com.iojh2021.persiandashboard'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
