plugins { id 'com.android.application' }

android {
    namespace 'com.iojh2021.persiandashboard'
    compileSdk 35

    defaultConfig {
        applicationId 'com.iojh2021.persiandashboard'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
